version: '3.7'

services:
  web:
    image: docker.pkg.github.com/cyrilhokage/cnouboue_portfolio/portfolio-image:master-85e8461
    ports:
      - "8020:8020"
      - "80:80"
      - "443:443"
    volumes:
      - media_data:/opt/app/cnouboue_portfolio/media/
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db


volumes:
  media_data:
  postgres_data:
