version: '3.7'

services:
  web:
    image: cyrilhokage/cnouboue_portfolio:latest
    ports:
      - "8020:8020"
      - "80:80"
      - "443:443"
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db


volumes:
  postgres_data:
