# Generated by Django 3.1.3 on 2020-11-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20191116_1409"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
