# Generated by Django 3.1.3 on 2021-02-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0003_auto_20210220_0226"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="synopsis",
            field=models.TextField(null=True),
        ),
    ]
