# Generated by Django 3.1.3 on 2021-02-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_program_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=70),
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=70),
        ),
    ]
