# Generated by Django 3.1.3 on 2021-03-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0009_auto_20210313_0403"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="watch_link",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_name", models.CharField(max_length=70)),
                (
                    "slug",
                    models.SlugField(default="default-slug-profile", max_length=80),
                ),
                (
                    "provider_tmdb_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "logo_path",
                    models.ImageField(
                        default="profile_pics/default.png", upload_to="profile_pics"
                    ),
                ),
                ("program", models.ManyToManyField(to="notebook.Program")),
            ],
        ),
    ]
