# Generated by Django 3.1.3 on 2021-03-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0010_auto_20210314_0149"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="logo_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="poster_path",
            field=models.URLField(null=True),
        ),
    ]
