# Generated by Django 3.1.3 on 2021-03-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0011_auto_20210314_0219"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="program",
        ),
        migrations.AddField(
            model_name="program",
            name="providers",
            field=models.ManyToManyField(to="notebook.Provider"),
        ),
    ]
