# Generated by Django 3.1.3 on 2021-03-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0012_auto_20210314_0223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="logo_path",
            field=models.ImageField(null=True, upload_to="providers_posters"),
        ),
    ]
