# Generated by Django 3.1.3 on 2021-03-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0013_auto_20210314_0231"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="provider_type",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
