# Generated by Django 3.1.3 on 2021-03-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0014_provider_provider_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["slug"]},
        ),
        migrations.AlterModelOptions(
            name="program",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={"ordering": ["provider_name"]},
        ),
        migrations.AlterField(
            model_name="program",
            name="poster_path",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="logo_path",
            field=models.ImageField(
                default="program_posters/poster_default.png",
                null=True,
                upload_to="providers_posters",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="logo_url",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
