# Generated by Django 3.1.3 on 2021-03-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0015_auto_20210314_0447"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                related_name="_profile_following_+", to="notebook.Profile"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="similars",
            field=models.ManyToManyField(
                related_name="_program_similars_+", to="notebook.Program"
            ),
        ),
    ]
